### ISSUE TITLE
retours

### ISSUE THREAD

**Issue by fabien-prudhomme** [philippe-vandermoere/skeleton#2]
1) Explication du dirrectory dans le lancement de la commande : 
Exemple --> 
{directory} : chemin absolu de lancement du script
{project name} : Nom du projet
Voutre projet final se trouvera donc dans : {directory}/{project name}/

2) L'option pour docker run est --rm et non -rm

3) Attention au "." dans l'url

**Comment by philippe-vandermoere** [comment]
Fix in #3
